"""Generates a typed, compile-time-constant Dart source file for one atlas.

The generated file declares one ``const SpriteAtlas`` value built from
the shared, hand-written runtime types in
``lib/models/sprite_atlas.dart`` (the Flutter integration seam) — it
never redeclares those classes itself, so multiple generated atlas files
can be imported into the same Dart program without a name collision.

Deterministic by construction: field order is fixed, floats are
formatted with a stable ``repr()``, and animations/frames are emitted in
the exact order [AnimationRecord]s were built in (itself deterministic —
see ``discovery.py``/``packing.py``'s own determinism guarantees).
Running the generator twice on identical input produces byte-identical
output.
"""

from __future__ import annotations

import re

from .models import AnimationRecord, FrameRect, LoopMode

_SEAM_IMPORT = "package:unified_math_tutor/models/sprite_atlas.dart"

_LOOP_MODE_DART = {
    LoopMode.ONCE: "SpriteLoopMode.once",
    LoopMode.LOOP: "SpriteLoopMode.loop",
    LoopMode.PING_PONG: "SpriteLoopMode.pingPong",
}


def _camel_case(identifier: str) -> str:
    parts = [p for p in re.split(r"[_/\-]", identifier) if p]
    if not parts:
        return "atlas"
    return parts[0].lower() + "".join(p[:1].upper() + p[1:].lower() for p in parts[1:])


def dart_const_name(atlas_id: str) -> str:
    return f"{_camel_case(atlas_id)}Atlas"


def _dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _dart_float(value: float) -> str:
    return repr(float(value))


def _frame_rect_dart(frame: FrameRect, indent: str) -> str:
    return (
        f"{indent}SpriteFrameRect(\n"
        f"{indent}  sourceFile: {_dart_string(frame.source_file)},\n"
        f"{indent}  sourceHash: {_dart_string(frame.source_hash)},\n"
        f"{indent}  x: {frame.x},\n"
        f"{indent}  y: {frame.y},\n"
        f"{indent}  width: {frame.width},\n"
        f"{indent}  height: {frame.height},\n"
        f"{indent}  originalWidth: {frame.original_width},\n"
        f"{indent}  originalHeight: {frame.original_height},\n"
        f"{indent}  trimmedOffsetX: {frame.trimmed_offset_x},\n"
        f"{indent}  trimmedOffsetY: {frame.trimmed_offset_y},\n"
        f"{indent}),\n"
    )


def _animation_dart(animation: AnimationRecord, indent: str) -> str:
    frames_dart = "".join(
        _frame_rect_dart(frame, indent + "    ") for frame in animation.frames
    )
    verified = "true" if animation.verified else "false"
    return (
        f"{indent}SpriteAnimation(\n"
        f"{indent}  assetId: {_dart_string(animation.asset_id)},\n"
        f"{indent}  atlasFile: {_dart_string(animation.atlas_file)},\n"
        f"{indent}  anchorX: {_dart_float(animation.anchor_x)},\n"
        f"{indent}  anchorY: {_dart_float(animation.anchor_y)},\n"
        f"{indent}  frameDurationMs: {animation.frame_duration_ms},\n"
        f"{indent}  loop: {_LOOP_MODE_DART[animation.loop]},\n"
        f"{indent}  reducedMotionFallbackFrame: {animation.reduced_motion_fallback_frame},\n"
        f"{indent}  contentVersion: {animation.content_version},\n"
        f"{indent}  verified: {verified},\n"
        f"{indent}  frames: [\n{frames_dart}{indent}  ],\n"
        f"{indent}),\n"
    )


def generate_dart_catalog(
    *,
    atlas_id: str,
    atlas_file: str,
    manifest_file: str,
    animations: list[AnimationRecord],
) -> str:
    """Renders the full, deterministic Dart source for one atlas's typed
    catalogue constant."""
    const_name = dart_const_name(atlas_id)
    animations_dart = "".join(_animation_dart(a, "    ") for a in animations)

    return (
        "// GENERATED FILE - DO NOT EDIT BY HAND.\n"
        f"// Generated by scripts/asset_pipeline for atlas '{atlas_id}'.\n"
        "// ignore_for_file: type=lint\n\n"
        f"import '{_SEAM_IMPORT}';\n\n"
        f"const {const_name} = SpriteAtlas(\n"
        f"  atlasId: {_dart_string(atlas_id)},\n"
        f"  atlasFile: {_dart_string(atlas_file)},\n"
        f"  manifestFile: {_dart_string(manifest_file)},\n"
        f"  animations: [\n{animations_dart}  ],\n"
        ");\n"
    )
