import 'package:flutter_shared_models/question_item.dart';

import '../models/continue_learning_checkpoint.dart';
import '../models/graph_question.dart';
import '../models/practice_session_restoration_payload.dart';
import 'jsonl_pack_loader.dart';
import 'pack_registry_service.dart';
import 'practice_pack_question_mapper.dart';

/// A validated, ready-to-use bundle for reopening a practice-session
/// checkpoint — never a raw route string or a callback. Everything in here
/// has already been checked against the live, currently-bundled content.
class ResolvedPracticeResume {
  const ResolvedPracticeResume({
    required this.checkpointId,
    required this.startedAtUtc,
    required this.resumeCount,
    required this.stage,
    required this.topicId,
    required this.questions,
    required this.graphsByQuestionId,
    required this.currentStep,
    required this.selectedIndices,
  });

  /// Carried through so the resumer never needs to re-read
  /// `ContinueLearningService.instance.currentCheckpoint` (which could in
  /// principle have changed between resolve-time and construct-time, e.g.
  /// a scope change) — this object is self-contained.
  final String checkpointId;
  final DateTime startedAtUtc;
  final int resumeCount;

  final String stage;
  final String? topicId;

  /// The full, ordered question list for this session — regenerated by
  /// reloading the pack and looking up each of the checkpoint's persisted
  /// ids, in order. Guaranteed to be the same length and order as when the
  /// checkpoint was saved, or this object would never have been produced.
  final List<QuestionItem> questions;
  final Map<String, GraphQuestion> graphsByQuestionId;

  /// Index of the next unanswered question — where the session resumes.
  final int currentStep;

  /// One entry per already-answered question (`questions[0..currentStep)`),
  /// in the same order — the learner's recorded choice for each.
  final List<int> selectedIndices;
}

/// The governed resume-destination mechanism for
/// `ContinueLearningActivityType.practiceSession` checkpoints.
///
/// This is deliberately narrow, not a generic deep-link/router framework:
/// it maps exactly one closed activity type to exactly one typed result,
/// validates every id against live content before returning anything, and
/// returns `null` — never throws, never navigates, never executes a stored
/// route string — when the checkpoint's content is missing, unsupported, or
/// malformed. A future activity type gets its own resolver function
/// alongside this one; this file is the pattern to copy, not a framework to
/// extend generically.
class ContinueLearningDestinationResolver {
  ContinueLearningDestinationResolver._();

  /// Resolves a practice-session checkpoint into ready-to-render content.
  /// Returns `null` (a controlled "unavailable" result) if:
  /// * the checkpoint is not a practice-session checkpoint;
  /// * the stage is no longer a valid selectable practice stage;
  /// * the restoration payload doesn't decode;
  /// * any persisted question id no longer exists in the reloaded pack.
  static Future<ResolvedPracticeResume?> resolvePracticeSession(
    ContinueLearningCheckpoint checkpoint,
  ) async {
    if (checkpoint.activityType !=
        ContinueLearningActivityType.practiceSession) {
      return null;
    }
    if (!PackRegistryService.practiceStages
        .map((s) => s.toLowerCase())
        .contains(checkpoint.curriculumLevel.toLowerCase())) {
      return null;
    }
    final payload = PracticeSessionRestorationPayload.tryDecode(
        checkpoint.restorationPayload);
    if (payload == null) return null;
    if (payload.questionIds.length != checkpoint.totalSteps) return null;
    if (payload.selectedIndices.length != checkpoint.currentStep) return null;

    try {
      final pack = await PackRegistryService.instance.forStage(
        checkpoint.curriculumLevel,
      );
      final allRecords = await JsonlPackLoader.instance.load(pack);
      final byId = <String, Map<String, dynamic>>{
        for (final record in allRecords)
          if (record['id'] is String) record['id'] as String: record,
      };

      final questions = <QuestionItem>[];
      final graphs = <String, GraphQuestion>{};
      for (final id in payload.questionIds) {
        final record = byId[id];
        if (record == null) {
          // Content the learner was mid-way through no longer exists in
          // the currently-bundled pack (e.g. content regenerated between
          // app versions) — fail closed rather than resuming into a
          // different question while pretending it's the original one.
          return null;
        }
        questions.add(questionFromPackJson(record));
        final graph = GraphQuestion.fromQuestionJson(record);
        if (graph != null) graphs[id] = graph;
      }

      return ResolvedPracticeResume(
        checkpointId: checkpoint.checkpointId,
        startedAtUtc: checkpoint.startedAtUtc,
        resumeCount: checkpoint.resumeCount,
        stage: checkpoint.curriculumLevel,
        topicId: checkpoint.topicId,
        questions: questions,
        graphsByQuestionId: graphs,
        currentStep: checkpoint.currentStep,
        selectedIndices: payload.selectedIndices,
      );
    } catch (_) {
      // Pack failed to load/parse — unavailable, not a crash.
      return null;
    }
  }
}
