/// The `ContinueLearningActivityType.practiceSession` restoration-payload
/// adapter: encodes/decodes the small, JSON-safe detail a practice-session
/// checkpoint needs to restore the exact same session, and nothing else.
///
/// Deliberately holds only integers and short id strings:
/// * [questionIds] — the ordered list of question ids selected for this
///   session. Practice sessions shuffle their question set at start time
///   with no stored seed (see `practice_screen.dart`'s `_loadSession`), so
///   the only way to reopen the *same* set in the *same* order is to
///   record the ids directly — there is nothing to regenerate from.
/// * [selectedIndices] — one integer per already-answered question (length
///   equals the checkpoint's `currentStep`), so a resumed session can
///   rebuild its answered-question list without ever persisting the
///   question text, option text, or explanation — all of that is
///   regenerated by reloading the pack and looking up each id in
///   [questionIds].
class PracticeSessionRestorationPayload {
  const PracticeSessionRestorationPayload({
    required this.questionIds,
    required this.selectedIndices,
  });

  final List<String> questionIds;
  final List<int> selectedIndices;

  Map<String, Object?> toJson() => {
        'questionIds': questionIds,
        'selectedIndices': selectedIndices,
      };

  /// Strict decode — `null` for anything malformed, matching
  /// [ContinueLearningCheckpoint.tryDecode]'s fail-closed policy.
  static PracticeSessionRestorationPayload? tryDecode(
      Map<String, Object?> json) {
    try {
      final rawIds = json['questionIds'];
      final rawIndices = json['selectedIndices'];
      if (rawIds is! List || rawIndices is! List) return null;
      if (rawIds.isEmpty) return null;
      if (rawIndices.length > rawIds.length) return null;

      final questionIds = <String>[];
      for (final value in rawIds) {
        if (value is! String || value.isEmpty) return null;
        questionIds.add(value);
      }
      final selectedIndices = <int>[];
      for (final value in rawIndices) {
        if (value is! int || value < 0) return null;
        selectedIndices.add(value);
      }
      return PracticeSessionRestorationPayload(
        questionIds: questionIds,
        selectedIndices: selectedIndices,
      );
    } catch (_) {
      return null;
    }
  }
}
